#!/bin/bash

if [ -z "$1" ] ; then
	echo "Usage: Backlightt <value (0.1 to 1.0)>"
	exit 1
fi

#DISPLAY=$(xrandr --current | grep "connected" | awk '{ print $1}')


xrandr --output eDP-1 --brightness "$1" 
